from setuptools import setup

setup(
    name='shareideas',
    version='1.0',
    long_description=__doc__,
    packages=['shareideas'],
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        'bcrypt',
        'blinker',
        'cffi',
        'click',
        'dnspython',
        'email-validator',
        'Flask',
        'Flask-Bcrypt',
        'Flask-Login',
        'Flask-Mail',
        'Flask-SQLAlchemy',
        'Flask-WTF',
        'greenlet',
        'idna',
        'itsdangerous',
        'Jinja2',
        'MarkupSafe',
        'Pillow',
        'pycparser',
        'six',
        'SQLAlchemy',
        'Werkzeug',
        'WTForms'
    ]
)
